
spring:
  batch:
    initialize-schema: always

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
        use_sql_comments: true

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

  datasource:
    username: connectuser
    password: connect123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://35.232.22.234:3306/connectdb?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8
    maximumPoolSize: 100
    minimumIdle: 100

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

coolsms:
  api:
    key: "NCSFFKZGLSBSZQDV"
    secret: "OFB5SOC7XNFIAC7BLN8G9UNIJYV7YCZR"
    send-no: "010-7173-1403"